use crate::compare_scenario;
use crate::scenario::{all_scenarios, ScenarioExpectation, ALL_CLI_FEATURES};
use crate::Comparison;

const MAX_MISMATCH_BLOCKS: usize = 12;
const MAX_MISMATCH_DIFF_LINES: usize = 80;
const MAX_MISMATCH_DIFF_CHARS: usize = 8_000;

#[derive(Clone, Debug)]
pub struct MatrixReport {
    pub comparisons: Vec<Comparison>,
}

impl MatrixReport {
    pub fn total(&self) -> usize {
        self.comparisons.len()
    }

    pub fn must_match_total(&self) -> usize {
        self.comparisons
            .iter()
            .filter(|entry| matches!(entry.scenario.expectation, ScenarioExpectation::MustMatch))
            .count()
    }

    pub fn known_gap_total(&self) -> usize {
        self.comparisons
            .iter()
            .filter(|entry| matches!(entry.scenario.expectation, ScenarioExpectation::KnownGap(_)))
            .count()
    }

    pub fn matched_total(&self) -> usize {
        self.comparisons
            .iter()
            .filter(|entry| entry.is_match())
            .count()
    }

    pub fn unexpected_mismatches(&self) -> Vec<&Comparison> {
        self.comparisons
            .iter()
            .filter(|entry| {
                matches!(entry.scenario.expectation, ScenarioExpectation::MustMatch)
                    && !entry.is_match()
            })
            .collect()
    }

    pub fn closed_gaps(&self) -> Vec<&Comparison> {
        self.comparisons
            .iter()
            .filter(|entry| {
                matches!(entry.scenario.expectation, ScenarioExpectation::KnownGap(_))
                    && entry.is_match()
            })
            .collect()
    }
}

pub fn run_matrix(fixture_override: Option<&str>) -> Result<MatrixReport, String> {
    let mut comparisons = Vec::with_capacity(all_scenarios().len());
    for scenario in all_scenarios() {
        comparisons.push(compare_scenario(*scenario, fixture_override)?);
    }
    Ok(MatrixReport { comparisons })
}

pub fn render_markdown_report(report: &MatrixReport) -> String {
    let mut out = String::new();
    out.push_str("# H265NAL CLI Feature Parity Report\n\n");
    out.push_str("Generated by `cargo run -p h265nal-parity -- report [--output <path>]`.\n\n");

    out.push_str("## Summary\n");
    out.push_str(&format!("- Total scenarios: {}\n", report.total()));
    out.push_str(&format!(
        "- Must-match scenarios: {}\n",
        report.must_match_total()
    ));
    out.push_str(&format!(
        "- Known-gap scenarios: {}\n",
        report.known_gap_total()
    ));
    out.push_str(&format!(
        "- Scenarios currently matching byte-for-byte: {}\n",
        report.matched_total()
    ));
    out.push_str(&format!(
        "- Unexpected regressions (must-match but mismatched): {}\n",
        report.unexpected_mismatches().len()
    ));
    out.push_str(&format!(
        "- Closed gaps (known-gap scenarios that now match): {}\n\n",
        report.closed_gaps().len()
    ));

    out.push_str("## Feature Coverage\n");
    out.push_str("| Feature | Scenario Count | Status |\n");
    out.push_str("|---|---:|---|\n");
    for feature in ALL_CLI_FEATURES {
        let rows: Vec<&Comparison> = report
            .comparisons
            .iter()
            .filter(|entry| entry.scenario.features.contains(&feature))
            .collect();
        let status = feature_status(&rows);
        out.push_str(&format!(
            "| `{}` | {} | {} |\n",
            feature.as_str(),
            rows.len(),
            status
        ));
    }
    out.push('\n');

    out.push_str("## Scenario Results\n");
    out.push_str("| Scenario | Expectation | Outcome | Notes |\n");
    out.push_str("|---|---|---|---|\n");
    for entry in &report.comparisons {
        let expectation = entry.scenario.expectation.label();
        let outcome = scenario_outcome_label(entry);
        let notes = entry
            .scenario
            .expectation
            .gap_note()
            .unwrap_or(entry.scenario.description);
        out.push_str(&format!(
            "| `{}` | `{}` | `{}` | {} |\n",
            entry.scenario.name, expectation, outcome, notes
        ));
    }
    out.push('\n');

    out.push_str("## Command Mapping\n");
    out.push_str("| Scenario | Baseline Command | Local Command |\n");
    out.push_str("|---|---|---|\n");
    for entry in &report.comparisons {
        out.push_str(&format!(
            "| `{}` | `{}` | `{}` |\n",
            entry.scenario.name,
            markdown_inline(&entry.baseline_output.command),
            markdown_inline(&entry.local_output.command)
        ));
    }
    out.push('\n');

    out.push_str("## Mismatch Diffs\n");
    let mismatches: Vec<&Comparison> = report
        .comparisons
        .iter()
        .filter(|entry| !entry.is_match())
        .collect();
    if mismatches.is_empty() {
        out.push_str("All scenarios matched byte-for-byte.\n");
    } else {
        out.push_str(
            "Each block is truncated to keep the report readable; rerun single scenarios for full output.\n\n",
        );
        let shown = mismatches.len().min(MAX_MISMATCH_BLOCKS);
        for entry in mismatches.iter().take(MAX_MISMATCH_BLOCKS) {
            out.push_str(&format!("### `{}`\n\n", entry.scenario.name));
            out.push_str("```text\n");
            if let Some(diagnostic) = &entry.diagnostic {
                let lines = truncate_lines(diagnostic, MAX_MISMATCH_DIFF_LINES);
                out.push_str(&truncate_chars(&lines, MAX_MISMATCH_DIFF_CHARS));
            }
            out.push_str("\n```\n\n");
        }
        if mismatches.len() > shown {
            out.push_str(&format!(
                "... {} additional mismatch diagnostics omitted from markdown output.\n",
                mismatches.len() - shown
            ));
        }
    }

    out
}

fn scenario_outcome_label(entry: &Comparison) -> &'static str {
    match (entry.is_match(), entry.scenario.expectation) {
        (true, ScenarioExpectation::MustMatch) => "match",
        (false, ScenarioExpectation::MustMatch) => "regression",
        (false, ScenarioExpectation::KnownGap(_)) => "expected_mismatch",
        (true, ScenarioExpectation::KnownGap(_)) => "gap_closed",
    }
}

fn feature_status(rows: &[&Comparison]) -> &'static str {
    if rows.is_empty() {
        return "uncovered";
    }

    if rows.iter().any(|entry| {
        matches!(entry.scenario.expectation, ScenarioExpectation::MustMatch) && !entry.is_match()
    }) {
        return "regression";
    }

    if rows.iter().any(|entry| {
        matches!(entry.scenario.expectation, ScenarioExpectation::KnownGap(_)) && !entry.is_match()
    }) {
        return "known_gaps";
    }

    if rows.iter().any(|entry| {
        matches!(entry.scenario.expectation, ScenarioExpectation::KnownGap(_)) && entry.is_match()
    }) {
        return "gap_closed";
    }

    "matched"
}

fn markdown_inline(value: &str) -> String {
    value.replace('`', "\\`")
}

fn truncate_lines(input: &str, max_lines: usize) -> String {
    let mut lines = input.lines();
    let mut out = String::new();
    for index in 0..max_lines {
        let Some(line) = lines.next() else {
            return out;
        };
        if index > 0 {
            out.push('\n');
        }
        out.push_str(line);
    }

    if lines.next().is_some() {
        out.push('\n');
        out.push_str("... (truncated)");
    }
    out
}

fn truncate_chars(input: &str, max_chars: usize) -> String {
    let total_chars = input.chars().count();
    if total_chars <= max_chars {
        return input.to_string();
    }

    let mut out = String::new();
    for (index, ch) in input.chars().enumerate() {
        if index >= max_chars {
            break;
        }
        out.push(ch);
    }
    out.push_str("\n... (truncated)");
    out
}

#[cfg(test)]
mod tests {
    use super::{truncate_chars, truncate_lines};

    #[test]
    fn truncate_lines_adds_marker_when_cut() {
        let input = "a\nb\nc\nd\n";
        let out = truncate_lines(input, 2);
        assert!(out.contains("a\nb"));
        assert!(out.contains("(truncated)"));
    }

    #[test]
    fn truncate_chars_adds_marker_when_cut() {
        let out = truncate_chars("abcdef", 3);
        assert!(out.starts_with("abc"));
        assert!(out.contains("(truncated)"));
    }
}
