use crate::error::{status_to_result, Error};
use crate::ffi::{self, RawProfileInfoFields, RawProfileTierLevelFields, RawSpsFields};
use crate::profile_tier_level::{ProfileInfoFields, ProfileTierLevelFields};

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct SpsFields {
    pub sps_video_parameter_set_id: u32,
    pub sps_max_sub_layers_minus1: u32,
    pub sps_temporal_id_nesting_flag: u32,
    pub profile_tier_level: ProfileTierLevelFields,
    pub sps_seq_parameter_set_id: u32,
    pub chroma_format_idc: u32,
    pub pic_width_in_luma_samples: u32,
    pub pic_height_in_luma_samples: u32,
    pub conformance_window_flag: u32,
    pub conf_win_left_offset: u32,
    pub conf_win_right_offset: u32,
    pub conf_win_top_offset: u32,
    pub conf_win_bottom_offset: u32,
    pub bit_depth_luma_minus8: u32,
    pub bit_depth_chroma_minus8: u32,
    pub log2_max_pic_order_cnt_lsb_minus4: u32,
    pub sps_sub_layer_ordering_info_present_flag: u32,
    pub sps_max_dec_pic_buffering_minus1_0: u32,
    pub sps_max_num_reorder_pics_0: u32,
    pub sps_max_latency_increase_plus1_0: u32,
    pub scaling_list_enabled_flag: u32,
    pub amp_enabled_flag: u32,
    pub sample_adaptive_offset_enabled_flag: u32,
    pub pcm_enabled_flag: u32,
    pub num_short_term_ref_pic_sets: u32,
    pub long_term_ref_pics_present_flag: u32,
    pub sps_temporal_mvp_enabled_flag: u32,
    pub strong_intra_smoothing_enabled_flag: u32,
    pub vui_parameters_present_flag: u32,
    pub vui_video_signal_type_present_flag: u32,
    pub vui_video_format: u32,
    pub vui_video_full_range_flag: u32,
    pub vui_colour_description_present_flag: u32,
    pub vui_colour_primaries: u32,
    pub vui_transfer_characteristics: u32,
    pub vui_matrix_coeffs: u32,
    pub vui_bitstream_restriction_flag: u32,
    pub vui_max_bytes_per_pic_denom: u32,
    pub vui_max_bits_per_min_cu_denom: u32,
    pub vui_log2_max_mv_length_horizontal: u32,
    pub vui_log2_max_mv_length_vertical: u32,
    pub sps_extension_present_flag: u32,
    pub sps_range_extension_flag: u32,
    pub sps_multilayer_extension_flag: u32,
    pub sps_3d_extension_flag: u32,
    pub sps_scc_extension_flag: u32,
    pub sps_extension_4bits: u32,
    pub pic_size_in_ctbs_y: u32,
}

/// Parses SPS and returns a parity-focused scalar field surface.
///
/// Native references:
/// - Declaration: `include/h265_sps_parser.h:166` (`ParseSps`)
/// - Unit test: `test/h265_sps_parser_unittest.cc:21`
/// - Unit test: `test/h265_sps_parser_unittest.cc:191`
pub fn sps_parse(data: &[u8]) -> Result<SpsFields, Error> {
    let mut raw = empty_raw_sps_fields();
    let status = unsafe { ffi::h265nal_sps_parse(data.as_ptr(), data.len(), &mut raw) };
    status_to_result(status)?;

    Ok(SpsFields {
        sps_video_parameter_set_id: raw.sps_video_parameter_set_id,
        sps_max_sub_layers_minus1: raw.sps_max_sub_layers_minus1,
        sps_temporal_id_nesting_flag: raw.sps_temporal_id_nesting_flag,
        profile_tier_level: to_profile_tier_level(raw.profile_tier_level),
        sps_seq_parameter_set_id: raw.sps_seq_parameter_set_id,
        chroma_format_idc: raw.chroma_format_idc,
        pic_width_in_luma_samples: raw.pic_width_in_luma_samples,
        pic_height_in_luma_samples: raw.pic_height_in_luma_samples,
        conformance_window_flag: raw.conformance_window_flag,
        conf_win_left_offset: raw.conf_win_left_offset,
        conf_win_right_offset: raw.conf_win_right_offset,
        conf_win_top_offset: raw.conf_win_top_offset,
        conf_win_bottom_offset: raw.conf_win_bottom_offset,
        bit_depth_luma_minus8: raw.bit_depth_luma_minus8,
        bit_depth_chroma_minus8: raw.bit_depth_chroma_minus8,
        log2_max_pic_order_cnt_lsb_minus4: raw.log2_max_pic_order_cnt_lsb_minus4,
        sps_sub_layer_ordering_info_present_flag: raw.sps_sub_layer_ordering_info_present_flag,
        sps_max_dec_pic_buffering_minus1_0: raw.sps_max_dec_pic_buffering_minus1_0,
        sps_max_num_reorder_pics_0: raw.sps_max_num_reorder_pics_0,
        sps_max_latency_increase_plus1_0: raw.sps_max_latency_increase_plus1_0,
        scaling_list_enabled_flag: raw.scaling_list_enabled_flag,
        amp_enabled_flag: raw.amp_enabled_flag,
        sample_adaptive_offset_enabled_flag: raw.sample_adaptive_offset_enabled_flag,
        pcm_enabled_flag: raw.pcm_enabled_flag,
        num_short_term_ref_pic_sets: raw.num_short_term_ref_pic_sets,
        long_term_ref_pics_present_flag: raw.long_term_ref_pics_present_flag,
        sps_temporal_mvp_enabled_flag: raw.sps_temporal_mvp_enabled_flag,
        strong_intra_smoothing_enabled_flag: raw.strong_intra_smoothing_enabled_flag,
        vui_parameters_present_flag: raw.vui_parameters_present_flag,
        vui_video_signal_type_present_flag: raw.vui_video_signal_type_present_flag,
        vui_video_format: raw.vui_video_format,
        vui_video_full_range_flag: raw.vui_video_full_range_flag,
        vui_colour_description_present_flag: raw.vui_colour_description_present_flag,
        vui_colour_primaries: raw.vui_colour_primaries,
        vui_transfer_characteristics: raw.vui_transfer_characteristics,
        vui_matrix_coeffs: raw.vui_matrix_coeffs,
        vui_bitstream_restriction_flag: raw.vui_bitstream_restriction_flag,
        vui_max_bytes_per_pic_denom: raw.vui_max_bytes_per_pic_denom,
        vui_max_bits_per_min_cu_denom: raw.vui_max_bits_per_min_cu_denom,
        vui_log2_max_mv_length_horizontal: raw.vui_log2_max_mv_length_horizontal,
        vui_log2_max_mv_length_vertical: raw.vui_log2_max_mv_length_vertical,
        sps_extension_present_flag: raw.sps_extension_present_flag,
        sps_range_extension_flag: raw.sps_range_extension_flag,
        sps_multilayer_extension_flag: raw.sps_multilayer_extension_flag,
        sps_3d_extension_flag: raw.sps_3d_extension_flag,
        sps_scc_extension_flag: raw.sps_scc_extension_flag,
        sps_extension_4bits: raw.sps_extension_4bits,
        pic_size_in_ctbs_y: raw.pic_size_in_ctbs_y,
    })
}

fn to_profile_tier_level(raw: RawProfileTierLevelFields) -> ProfileTierLevelFields {
    ProfileTierLevelFields {
        general: ProfileInfoFields {
            profile_space: raw.general.profile_space,
            tier_flag: raw.general.tier_flag,
            profile_idc: raw.general.profile_idc,
            profile_compatibility_flag: raw.general.profile_compatibility_flag,
            progressive_source_flag: raw.general.progressive_source_flag,
            interlaced_source_flag: raw.general.interlaced_source_flag,
            non_packed_constraint_flag: raw.general.non_packed_constraint_flag,
            frame_only_constraint_flag: raw.general.frame_only_constraint_flag,
            max_12bit_constraint_flag: raw.general.max_12bit_constraint_flag,
            max_10bit_constraint_flag: raw.general.max_10bit_constraint_flag,
            max_8bit_constraint_flag: raw.general.max_8bit_constraint_flag,
            max_422chroma_constraint_flag: raw.general.max_422chroma_constraint_flag,
            max_420chroma_constraint_flag: raw.general.max_420chroma_constraint_flag,
            max_monochrome_constraint_flag: raw.general.max_monochrome_constraint_flag,
            intra_constraint_flag: raw.general.intra_constraint_flag,
            one_picture_only_constraint_flag: raw.general.one_picture_only_constraint_flag,
            lower_bit_rate_constraint_flag: raw.general.lower_bit_rate_constraint_flag,
            max_14bit_constraint_flag: raw.general.max_14bit_constraint_flag,
            reserved_zero_33bits: raw.general.reserved_zero_33bits,
            reserved_zero_34bits: raw.general.reserved_zero_34bits,
            reserved_zero_43bits: raw.general.reserved_zero_43bits,
            inbld_flag: raw.general.inbld_flag,
            reserved_zero_bit: raw.general.reserved_zero_bit,
        },
        general_level_idc: raw.general_level_idc,
        sub_layer_profile_present_flag_size: raw.sub_layer_profile_present_flag_size,
        sub_layer_level_present_flag_size: raw.sub_layer_level_present_flag_size,
        reserved_zero_2bits_size: raw.reserved_zero_2bits_size,
        sub_layer_size: raw.sub_layer_size,
    }
}

fn empty_raw_sps_fields() -> RawSpsFields {
    RawSpsFields {
        sps_video_parameter_set_id: 0,
        sps_max_sub_layers_minus1: 0,
        sps_temporal_id_nesting_flag: 0,
        profile_tier_level: RawProfileTierLevelFields {
            general: RawProfileInfoFields {
                profile_space: 0,
                tier_flag: 0,
                profile_idc: 0,
                profile_compatibility_flag: [0; 32],
                progressive_source_flag: 0,
                interlaced_source_flag: 0,
                non_packed_constraint_flag: 0,
                frame_only_constraint_flag: 0,
                max_12bit_constraint_flag: 0,
                max_10bit_constraint_flag: 0,
                max_8bit_constraint_flag: 0,
                max_422chroma_constraint_flag: 0,
                max_420chroma_constraint_flag: 0,
                max_monochrome_constraint_flag: 0,
                intra_constraint_flag: 0,
                one_picture_only_constraint_flag: 0,
                lower_bit_rate_constraint_flag: 0,
                max_14bit_constraint_flag: 0,
                reserved_zero_33bits: 0,
                reserved_zero_34bits: 0,
                reserved_zero_43bits: 0,
                inbld_flag: 0,
                reserved_zero_bit: 0,
            },
            general_level_idc: 0,
            sub_layer_profile_present_flag_size: 0,
            sub_layer_level_present_flag_size: 0,
            reserved_zero_2bits_size: 0,
            sub_layer_size: 0,
        },
        sps_seq_parameter_set_id: 0,
        chroma_format_idc: 0,
        pic_width_in_luma_samples: 0,
        pic_height_in_luma_samples: 0,
        conformance_window_flag: 0,
        conf_win_left_offset: 0,
        conf_win_right_offset: 0,
        conf_win_top_offset: 0,
        conf_win_bottom_offset: 0,
        bit_depth_luma_minus8: 0,
        bit_depth_chroma_minus8: 0,
        log2_max_pic_order_cnt_lsb_minus4: 0,
        sps_sub_layer_ordering_info_present_flag: 0,
        sps_max_dec_pic_buffering_minus1_0: 0,
        sps_max_num_reorder_pics_0: 0,
        sps_max_latency_increase_plus1_0: 0,
        scaling_list_enabled_flag: 0,
        amp_enabled_flag: 0,
        sample_adaptive_offset_enabled_flag: 0,
        pcm_enabled_flag: 0,
        num_short_term_ref_pic_sets: 0,
        long_term_ref_pics_present_flag: 0,
        sps_temporal_mvp_enabled_flag: 0,
        strong_intra_smoothing_enabled_flag: 0,
        vui_parameters_present_flag: 0,
        vui_video_signal_type_present_flag: 0,
        vui_video_format: 0,
        vui_video_full_range_flag: 0,
        vui_colour_description_present_flag: 0,
        vui_colour_primaries: 0,
        vui_transfer_characteristics: 0,
        vui_matrix_coeffs: 0,
        vui_bitstream_restriction_flag: 0,
        vui_max_bytes_per_pic_denom: 0,
        vui_max_bits_per_min_cu_denom: 0,
        vui_log2_max_mv_length_horizontal: 0,
        vui_log2_max_mv_length_vertical: 0,
        sps_extension_present_flag: 0,
        sps_range_extension_flag: 0,
        sps_multilayer_extension_flag: 0,
        sps_3d_extension_flag: 0,
        sps_scc_extension_flag: 0,
        sps_extension_4bits: 0,
        pic_size_in_ctbs_y: 0,
    }
}
