use crate::error::{status_to_result, Error};
use crate::ffi::{self, RawProfileInfoFields, RawProfileTierLevelFields, RawVpsFields};
use crate::profile_tier_level::{ProfileInfoFields, ProfileTierLevelFields};

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct VpsFields {
    pub vps_video_parameter_set_id: u32,
    pub vps_base_layer_internal_flag: u32,
    pub vps_base_layer_available_flag: u32,
    pub vps_max_layers_minus1: u32,
    pub vps_max_sub_layers_minus1: u32,
    pub vps_temporal_id_nesting_flag: u32,
    pub vps_reserved_0xffff_16bits: u32,
    pub profile_tier_level: ProfileTierLevelFields,
    pub vps_sub_layer_ordering_info_present_flag: u32,
    pub vps_max_dec_pic_buffering_minus1_size: usize,
    pub vps_max_dec_pic_buffering_minus1: [u32; 8],
    pub vps_max_num_reorder_pics_size: usize,
    pub vps_max_num_reorder_pics: [u32; 8],
    pub vps_max_latency_increase_plus1_size: usize,
    pub vps_max_latency_increase_plus1: [u32; 8],
    pub vps_max_layer_id: u32,
    pub vps_num_layer_sets_minus1: u32,
    pub layer_id_included_flag_size: usize,
    pub layer_id_included_flag_row_width: u32,
    pub layer_id_included_flag_row0_mask: u64,
    pub layer_id_included_flag_row1_mask: u64,
    pub vps_timing_info_present_flag: u32,
    pub vps_num_units_in_tick: u32,
    pub vps_time_scale: u32,
    pub vps_poc_proportional_to_timing_flag: u32,
    pub vps_num_ticks_poc_diff_one_minus1: u32,
    pub vps_num_hrd_parameters: u32,
    pub hrd_layer_set_idx_size: usize,
    pub cprms_present_flag_size: usize,
    pub vps_extension_flag: u32,
    pub vps_extension_data_flag: u32,
}

pub fn vps_parse(data: &[u8]) -> Result<VpsFields, Error> {
    let mut raw = empty_raw_vps_fields();
    let status = unsafe { ffi::h265nal_vps_parse(data.as_ptr(), data.len(), &mut raw) };
    status_to_result(status)?;

    Ok(VpsFields {
        vps_video_parameter_set_id: raw.vps_video_parameter_set_id,
        vps_base_layer_internal_flag: raw.vps_base_layer_internal_flag,
        vps_base_layer_available_flag: raw.vps_base_layer_available_flag,
        vps_max_layers_minus1: raw.vps_max_layers_minus1,
        vps_max_sub_layers_minus1: raw.vps_max_sub_layers_minus1,
        vps_temporal_id_nesting_flag: raw.vps_temporal_id_nesting_flag,
        vps_reserved_0xffff_16bits: raw.vps_reserved_0xffff_16bits,
        profile_tier_level: to_profile_tier_level(raw.profile_tier_level),
        vps_sub_layer_ordering_info_present_flag: raw.vps_sub_layer_ordering_info_present_flag,
        vps_max_dec_pic_buffering_minus1_size: raw.vps_max_dec_pic_buffering_minus1_size,
        vps_max_dec_pic_buffering_minus1: raw.vps_max_dec_pic_buffering_minus1,
        vps_max_num_reorder_pics_size: raw.vps_max_num_reorder_pics_size,
        vps_max_num_reorder_pics: raw.vps_max_num_reorder_pics,
        vps_max_latency_increase_plus1_size: raw.vps_max_latency_increase_plus1_size,
        vps_max_latency_increase_plus1: raw.vps_max_latency_increase_plus1,
        vps_max_layer_id: raw.vps_max_layer_id,
        vps_num_layer_sets_minus1: raw.vps_num_layer_sets_minus1,
        layer_id_included_flag_size: raw.layer_id_included_flag_size,
        layer_id_included_flag_row_width: raw.layer_id_included_flag_row_width,
        layer_id_included_flag_row0_mask: raw.layer_id_included_flag_row0_mask,
        layer_id_included_flag_row1_mask: raw.layer_id_included_flag_row1_mask,
        vps_timing_info_present_flag: raw.vps_timing_info_present_flag,
        vps_num_units_in_tick: raw.vps_num_units_in_tick,
        vps_time_scale: raw.vps_time_scale,
        vps_poc_proportional_to_timing_flag: raw.vps_poc_proportional_to_timing_flag,
        vps_num_ticks_poc_diff_one_minus1: raw.vps_num_ticks_poc_diff_one_minus1,
        vps_num_hrd_parameters: raw.vps_num_hrd_parameters,
        hrd_layer_set_idx_size: raw.hrd_layer_set_idx_size,
        cprms_present_flag_size: raw.cprms_present_flag_size,
        vps_extension_flag: raw.vps_extension_flag,
        vps_extension_data_flag: raw.vps_extension_data_flag,
    })
}

fn to_profile_tier_level(raw: RawProfileTierLevelFields) -> ProfileTierLevelFields {
    ProfileTierLevelFields {
        general: ProfileInfoFields {
            profile_space: raw.general.profile_space,
            tier_flag: raw.general.tier_flag,
            profile_idc: raw.general.profile_idc,
            profile_compatibility_flag: raw.general.profile_compatibility_flag,
            progressive_source_flag: raw.general.progressive_source_flag,
            interlaced_source_flag: raw.general.interlaced_source_flag,
            non_packed_constraint_flag: raw.general.non_packed_constraint_flag,
            frame_only_constraint_flag: raw.general.frame_only_constraint_flag,
            max_12bit_constraint_flag: raw.general.max_12bit_constraint_flag,
            max_10bit_constraint_flag: raw.general.max_10bit_constraint_flag,
            max_8bit_constraint_flag: raw.general.max_8bit_constraint_flag,
            max_422chroma_constraint_flag: raw.general.max_422chroma_constraint_flag,
            max_420chroma_constraint_flag: raw.general.max_420chroma_constraint_flag,
            max_monochrome_constraint_flag: raw.general.max_monochrome_constraint_flag,
            intra_constraint_flag: raw.general.intra_constraint_flag,
            one_picture_only_constraint_flag: raw.general.one_picture_only_constraint_flag,
            lower_bit_rate_constraint_flag: raw.general.lower_bit_rate_constraint_flag,
            max_14bit_constraint_flag: raw.general.max_14bit_constraint_flag,
            reserved_zero_33bits: raw.general.reserved_zero_33bits,
            reserved_zero_34bits: raw.general.reserved_zero_34bits,
            reserved_zero_43bits: raw.general.reserved_zero_43bits,
            inbld_flag: raw.general.inbld_flag,
            reserved_zero_bit: raw.general.reserved_zero_bit,
        },
        general_level_idc: raw.general_level_idc,
        sub_layer_profile_present_flag_size: raw.sub_layer_profile_present_flag_size,
        sub_layer_level_present_flag_size: raw.sub_layer_level_present_flag_size,
        reserved_zero_2bits_size: raw.reserved_zero_2bits_size,
        sub_layer_size: raw.sub_layer_size,
    }
}

fn empty_raw_vps_fields() -> RawVpsFields {
    RawVpsFields {
        vps_video_parameter_set_id: 0,
        vps_base_layer_internal_flag: 0,
        vps_base_layer_available_flag: 0,
        vps_max_layers_minus1: 0,
        vps_max_sub_layers_minus1: 0,
        vps_temporal_id_nesting_flag: 0,
        vps_reserved_0xffff_16bits: 0,
        profile_tier_level: RawProfileTierLevelFields {
            general: RawProfileInfoFields {
                profile_space: 0,
                tier_flag: 0,
                profile_idc: 0,
                profile_compatibility_flag: [0; 32],
                progressive_source_flag: 0,
                interlaced_source_flag: 0,
                non_packed_constraint_flag: 0,
                frame_only_constraint_flag: 0,
                max_12bit_constraint_flag: 0,
                max_10bit_constraint_flag: 0,
                max_8bit_constraint_flag: 0,
                max_422chroma_constraint_flag: 0,
                max_420chroma_constraint_flag: 0,
                max_monochrome_constraint_flag: 0,
                intra_constraint_flag: 0,
                one_picture_only_constraint_flag: 0,
                lower_bit_rate_constraint_flag: 0,
                max_14bit_constraint_flag: 0,
                reserved_zero_33bits: 0,
                reserved_zero_34bits: 0,
                reserved_zero_43bits: 0,
                inbld_flag: 0,
                reserved_zero_bit: 0,
            },
            general_level_idc: 0,
            sub_layer_profile_present_flag_size: 0,
            sub_layer_level_present_flag_size: 0,
            reserved_zero_2bits_size: 0,
            sub_layer_size: 0,
        },
        vps_sub_layer_ordering_info_present_flag: 0,
        vps_max_dec_pic_buffering_minus1_size: 0,
        vps_max_dec_pic_buffering_minus1: [0; 8],
        vps_max_num_reorder_pics_size: 0,
        vps_max_num_reorder_pics: [0; 8],
        vps_max_latency_increase_plus1_size: 0,
        vps_max_latency_increase_plus1: [0; 8],
        vps_max_layer_id: 0,
        vps_num_layer_sets_minus1: 0,
        layer_id_included_flag_size: 0,
        layer_id_included_flag_row_width: 0,
        layer_id_included_flag_row0_mask: 0,
        layer_id_included_flag_row1_mask: 0,
        vps_timing_info_present_flag: 0,
        vps_num_units_in_tick: 0,
        vps_time_scale: 0,
        vps_poc_proportional_to_timing_flag: 0,
        vps_num_ticks_poc_diff_one_minus1: 0,
        vps_num_hrd_parameters: 0,
        hrd_layer_set_idx_size: 0,
        cprms_present_flag_size: 0,
        vps_extension_flag: 0,
        vps_extension_data_flag: 0,
    }
}
