use crate::error::{status_to_result, Error};
use crate::ffi::{self, RawSubLayerHrdParametersFields, RawVuiParametersFields};
use crate::sub_layer_hrd_parameters::SubLayerHrdParametersFields;

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct VuiParametersFields {
    pub aspect_ratio_info_present_flag: u32,
    pub aspect_ratio_idc: u32,
    pub sar_width: u32,
    pub sar_height: u32,
    pub overscan_info_present_flag: u32,
    pub video_signal_type_present_flag: u32,
    pub video_format: u32,
    pub video_full_range_flag: u32,
    pub colour_description_present_flag: u32,
    pub colour_primaries: u32,
    pub transfer_characteristics: u32,
    pub matrix_coeffs: u32,
    pub chroma_loc_info_present_flag: u32,
    pub neutral_chroma_indication_flag: u32,
    pub field_seq_flag: u32,
    pub frame_field_info_present_flag: u32,
    pub default_display_window_flag: u32,
    pub vui_timing_info_present_flag: u32,
    pub vui_num_units_in_tick: u32,
    pub vui_time_scale: u32,
    pub vui_poc_proportional_to_timing_flag: u32,
    pub vui_hrd_parameters_present_flag: u32,
    pub bitstream_restriction_flag: u32,
    pub tiles_fixed_structure_flag: u32,
    pub motion_vectors_over_pic_boundaries_flag: u32,
    pub restricted_ref_pic_lists_flag: u32,
    pub min_spatial_segmentation_idc: u32,
    pub max_bytes_per_pic_denom: u32,
    pub max_bits_per_min_cu_denom: u32,
    pub log2_max_mv_length_horizontal: u32,
    pub log2_max_mv_length_vertical: u32,
    pub has_hrd_parameters: u32,
    pub hrd_nal_hrd_parameters_present_flag: u32,
    pub hrd_vcl_hrd_parameters_present_flag: u32,
    pub hrd_sub_pic_hrd_params_present_flag: u32,
    pub hrd_tick_divisor_minus2: u32,
    pub hrd_du_cpb_removal_delay_increment_length_minus1: u32,
    pub hrd_sub_pic_cpb_params_in_pic_timing_sei_flag: u32,
    pub hrd_dpb_output_delay_du_length_minus1: u32,
    pub hrd_bit_rate_scale: u32,
    pub hrd_cpb_size_scale: u32,
    pub hrd_cpb_size_du_scale: u32,
    pub hrd_initial_cpb_removal_delay_length_minus1: u32,
    pub hrd_au_cpb_removal_delay_length_minus1: u32,
    pub hrd_dpb_output_delay_length_minus1: u32,
    pub hrd_fixed_pic_rate_general_flag_size: usize,
    pub hrd_fixed_pic_rate_general_flag: [u32; 8],
    pub hrd_fixed_pic_rate_within_cvs_flag_size: usize,
    pub hrd_fixed_pic_rate_within_cvs_flag: [u32; 8],
    pub hrd_elemental_duration_in_tc_minus1_size: usize,
    pub hrd_elemental_duration_in_tc_minus1: [u32; 8],
    pub hrd_low_delay_hrd_flag_size: usize,
    pub hrd_low_delay_hrd_flag: [u32; 8],
    pub hrd_cpb_cnt_minus1_size: usize,
    pub hrd_cpb_cnt_minus1: [u32; 8],
    pub hrd_sub_layer_hrd_parameters_vector_size: usize,
    pub hrd_sub_layer_hrd_parameters_0_present: u32,
    pub hrd_sub_layer_hrd_parameters_0: SubLayerHrdParametersFields,
}

pub fn vui_parameters_parse(
    data: &[u8],
    sps_max_sub_layers_minus1: u32,
) -> Result<VuiParametersFields, Error> {
    let mut raw = empty_raw_vui_parameters_fields();
    let status = unsafe {
        ffi::h265nal_vui_parameters_parse(
            data.as_ptr(),
            data.len(),
            sps_max_sub_layers_minus1,
            &mut raw,
        )
    };
    status_to_result(status)?;

    Ok(VuiParametersFields {
        aspect_ratio_info_present_flag: raw.aspect_ratio_info_present_flag,
        aspect_ratio_idc: raw.aspect_ratio_idc,
        sar_width: raw.sar_width,
        sar_height: raw.sar_height,
        overscan_info_present_flag: raw.overscan_info_present_flag,
        video_signal_type_present_flag: raw.video_signal_type_present_flag,
        video_format: raw.video_format,
        video_full_range_flag: raw.video_full_range_flag,
        colour_description_present_flag: raw.colour_description_present_flag,
        colour_primaries: raw.colour_primaries,
        transfer_characteristics: raw.transfer_characteristics,
        matrix_coeffs: raw.matrix_coeffs,
        chroma_loc_info_present_flag: raw.chroma_loc_info_present_flag,
        neutral_chroma_indication_flag: raw.neutral_chroma_indication_flag,
        field_seq_flag: raw.field_seq_flag,
        frame_field_info_present_flag: raw.frame_field_info_present_flag,
        default_display_window_flag: raw.default_display_window_flag,
        vui_timing_info_present_flag: raw.vui_timing_info_present_flag,
        vui_num_units_in_tick: raw.vui_num_units_in_tick,
        vui_time_scale: raw.vui_time_scale,
        vui_poc_proportional_to_timing_flag: raw.vui_poc_proportional_to_timing_flag,
        vui_hrd_parameters_present_flag: raw.vui_hrd_parameters_present_flag,
        bitstream_restriction_flag: raw.bitstream_restriction_flag,
        tiles_fixed_structure_flag: raw.tiles_fixed_structure_flag,
        motion_vectors_over_pic_boundaries_flag: raw.motion_vectors_over_pic_boundaries_flag,
        restricted_ref_pic_lists_flag: raw.restricted_ref_pic_lists_flag,
        min_spatial_segmentation_idc: raw.min_spatial_segmentation_idc,
        max_bytes_per_pic_denom: raw.max_bytes_per_pic_denom,
        max_bits_per_min_cu_denom: raw.max_bits_per_min_cu_denom,
        log2_max_mv_length_horizontal: raw.log2_max_mv_length_horizontal,
        log2_max_mv_length_vertical: raw.log2_max_mv_length_vertical,
        has_hrd_parameters: raw.has_hrd_parameters,
        hrd_nal_hrd_parameters_present_flag: raw.hrd_nal_hrd_parameters_present_flag,
        hrd_vcl_hrd_parameters_present_flag: raw.hrd_vcl_hrd_parameters_present_flag,
        hrd_sub_pic_hrd_params_present_flag: raw.hrd_sub_pic_hrd_params_present_flag,
        hrd_tick_divisor_minus2: raw.hrd_tick_divisor_minus2,
        hrd_du_cpb_removal_delay_increment_length_minus1: raw
            .hrd_du_cpb_removal_delay_increment_length_minus1,
        hrd_sub_pic_cpb_params_in_pic_timing_sei_flag: raw
            .hrd_sub_pic_cpb_params_in_pic_timing_sei_flag,
        hrd_dpb_output_delay_du_length_minus1: raw.hrd_dpb_output_delay_du_length_minus1,
        hrd_bit_rate_scale: raw.hrd_bit_rate_scale,
        hrd_cpb_size_scale: raw.hrd_cpb_size_scale,
        hrd_cpb_size_du_scale: raw.hrd_cpb_size_du_scale,
        hrd_initial_cpb_removal_delay_length_minus1: raw
            .hrd_initial_cpb_removal_delay_length_minus1,
        hrd_au_cpb_removal_delay_length_minus1: raw.hrd_au_cpb_removal_delay_length_minus1,
        hrd_dpb_output_delay_length_minus1: raw.hrd_dpb_output_delay_length_minus1,
        hrd_fixed_pic_rate_general_flag_size: raw.hrd_fixed_pic_rate_general_flag_size,
        hrd_fixed_pic_rate_general_flag: raw.hrd_fixed_pic_rate_general_flag,
        hrd_fixed_pic_rate_within_cvs_flag_size: raw.hrd_fixed_pic_rate_within_cvs_flag_size,
        hrd_fixed_pic_rate_within_cvs_flag: raw.hrd_fixed_pic_rate_within_cvs_flag,
        hrd_elemental_duration_in_tc_minus1_size: raw.hrd_elemental_duration_in_tc_minus1_size,
        hrd_elemental_duration_in_tc_minus1: raw.hrd_elemental_duration_in_tc_minus1,
        hrd_low_delay_hrd_flag_size: raw.hrd_low_delay_hrd_flag_size,
        hrd_low_delay_hrd_flag: raw.hrd_low_delay_hrd_flag,
        hrd_cpb_cnt_minus1_size: raw.hrd_cpb_cnt_minus1_size,
        hrd_cpb_cnt_minus1: raw.hrd_cpb_cnt_minus1,
        hrd_sub_layer_hrd_parameters_vector_size: raw.hrd_sub_layer_hrd_parameters_vector_size,
        hrd_sub_layer_hrd_parameters_0_present: raw.hrd_sub_layer_hrd_parameters_0_present,
        hrd_sub_layer_hrd_parameters_0: sub_layer_from_raw(raw.hrd_sub_layer_hrd_parameters_0),
    })
}

fn sub_layer_from_raw(raw: RawSubLayerHrdParametersFields) -> SubLayerHrdParametersFields {
    SubLayerHrdParametersFields {
        sub_layer_id: raw.sub_layer_id,
        cpb_cnt: raw.cpb_cnt,
        sub_pic_hrd_params_present_flag: raw.sub_pic_hrd_params_present_flag,
        bit_rate_value_minus1_size: raw.bit_rate_value_minus1_size,
        bit_rate_value_minus1: raw.bit_rate_value_minus1,
        cpb_size_value_minus1_size: raw.cpb_size_value_minus1_size,
        cpb_size_value_minus1: raw.cpb_size_value_minus1,
        cpb_size_du_value_minus1_size: raw.cpb_size_du_value_minus1_size,
        cpb_size_du_value_minus1: raw.cpb_size_du_value_minus1,
        bit_rate_du_value_minus1_size: raw.bit_rate_du_value_minus1_size,
        bit_rate_du_value_minus1: raw.bit_rate_du_value_minus1,
        cbr_flag_size: raw.cbr_flag_size,
        cbr_flag: raw.cbr_flag,
    }
}

fn empty_raw_vui_parameters_fields() -> RawVuiParametersFields {
    RawVuiParametersFields {
        sps_max_sub_layers_minus1: 0,
        aspect_ratio_info_present_flag: 0,
        aspect_ratio_idc: 0,
        sar_width: 0,
        sar_height: 0,
        overscan_info_present_flag: 0,
        overscan_appropriate_flag: 0,
        video_signal_type_present_flag: 0,
        video_format: 0,
        video_full_range_flag: 0,
        colour_description_present_flag: 0,
        colour_primaries: 0,
        transfer_characteristics: 0,
        matrix_coeffs: 0,
        chroma_loc_info_present_flag: 0,
        chroma_sample_loc_type_top_field: 0,
        chroma_sample_loc_type_bottom_field: 0,
        neutral_chroma_indication_flag: 0,
        field_seq_flag: 0,
        frame_field_info_present_flag: 0,
        default_display_window_flag: 0,
        def_disp_win_left_offset: 0,
        def_disp_win_right_offset: 0,
        def_disp_win_top_offset: 0,
        def_disp_win_bottom_offset: 0,
        vui_timing_info_present_flag: 0,
        vui_num_units_in_tick: 0,
        vui_time_scale: 0,
        vui_poc_proportional_to_timing_flag: 0,
        vui_num_ticks_poc_diff_one_minus1: 0,
        vui_hrd_parameters_present_flag: 0,
        bitstream_restriction_flag: 0,
        tiles_fixed_structure_flag: 0,
        motion_vectors_over_pic_boundaries_flag: 0,
        restricted_ref_pic_lists_flag: 0,
        min_spatial_segmentation_idc: 0,
        max_bytes_per_pic_denom: 0,
        max_bits_per_min_cu_denom: 0,
        log2_max_mv_length_horizontal: 0,
        log2_max_mv_length_vertical: 0,
        has_hrd_parameters: 0,
        hrd_nal_hrd_parameters_present_flag: 0,
        hrd_vcl_hrd_parameters_present_flag: 0,
        hrd_sub_pic_hrd_params_present_flag: 0,
        hrd_tick_divisor_minus2: 0,
        hrd_du_cpb_removal_delay_increment_length_minus1: 0,
        hrd_sub_pic_cpb_params_in_pic_timing_sei_flag: 0,
        hrd_dpb_output_delay_du_length_minus1: 0,
        hrd_bit_rate_scale: 0,
        hrd_cpb_size_scale: 0,
        hrd_cpb_size_du_scale: 0,
        hrd_initial_cpb_removal_delay_length_minus1: 0,
        hrd_au_cpb_removal_delay_length_minus1: 0,
        hrd_dpb_output_delay_length_minus1: 0,
        hrd_fixed_pic_rate_general_flag_size: 0,
        hrd_fixed_pic_rate_general_flag: [0; 8],
        hrd_fixed_pic_rate_within_cvs_flag_size: 0,
        hrd_fixed_pic_rate_within_cvs_flag: [0; 8],
        hrd_elemental_duration_in_tc_minus1_size: 0,
        hrd_elemental_duration_in_tc_minus1: [0; 8],
        hrd_low_delay_hrd_flag_size: 0,
        hrd_low_delay_hrd_flag: [0; 8],
        hrd_cpb_cnt_minus1_size: 0,
        hrd_cpb_cnt_minus1: [0; 8],
        hrd_sub_layer_hrd_parameters_vector_size: 0,
        hrd_sub_layer_hrd_parameters_0_present: 0,
        hrd_sub_layer_hrd_parameters_0: RawSubLayerHrdParametersFields {
            sub_layer_id: 0,
            cpb_cnt: 0,
            sub_pic_hrd_params_present_flag: 0,
            bit_rate_value_minus1_size: 0,
            bit_rate_value_minus1: [0; 32],
            cpb_size_value_minus1_size: 0,
            cpb_size_value_minus1: [0; 32],
            cpb_size_du_value_minus1_size: 0,
            cpb_size_du_value_minus1: [0; 32],
            bit_rate_du_value_minus1_size: 0,
            bit_rate_du_value_minus1: [0; 32],
            cbr_flag_size: 0,
            cbr_flag: [0; 32],
        },
    }
}
